### ISSUE TITLE
Docker compose-dev doesn't track manager files

### ISSUE THREAD

**Issue by HeitorMatt** [harena-lab/harena-space#238]
Docker-compose-dev (https://github.com/datasci4health/harena-space/blob/master/docker-compose-dev.yml) doesn't track harena-manager files. 
This code works when executing the harena manager docker-compose individually, but not with harena-space's docker-compose-dev (It only tracks harena-space changes): 
`volumes:
      - ./src/adonisjs:/app`

Need help to fix this, it really annoying and counter-productive having to build harena-manager every time I make a change in the code. Any suggestions @matheusmota ?

**Comment by faguim** [comment]
I dont't know if a docker-compose application could compile source code from another project (i.e., another folder in filesystem). 

I guess that always it would be need to rebuild the image of sub-containers called by the main container defined on `docker-compose-dev.yml`. 
But , i am not sure of this.
